package gr.army.usermanagement.dao;


import gr.army.usermanagement.datamodel.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 *
 * @author Panagiotis Gouvas (KEPYES 28/5/2012)
 */
public interface UserRepository extends JpaRepository<User,String>{
    
    /*
     * Will produce autogenerated Query
     */
    public User findByUserId(String userid);

    public User findByUserIdAndDorCode(String userid,Long dorcode);    
    
}